import type { Vehicle } from '../../core/types'

// Civilian and fighter aircraft; specs verified against Wikipedia (sv/en) and flugzeuginfo.net.
// Variants: Gripen C, Viggen JA 37 (speed), F/A-18A-D, F-15 (Eagle), Boeing 737-800, Airbus A320 (with sharklets).
// topSpeedKmh is only given where a source states km/h; Mach-only figures are omitted.
export const AIRCRAFT: Vehicle[] = [
  {
    id: 'gripen',
    name: 'Saab JAS 39 Gripen',
    shortName: 'Gripen',
    category: 'fighter',
    country: 'Sverige',
    swedish: true,
    facts: [
      'Gripen är ett svenskt flygplan från Saab.',
      'Gripen har en motor.',
      'Gripen har små vingar längst fram.',
      'Gripen kan landa på vanliga vägar.',
    ],
    specs: { firstYear: 1988, engines: 1, lengthM: 14.1, wingspanM: 8.4 },
    sources: [
      'https://sv.wikipedia.org/wiki/Saab_39_Gripen',
      'https://en.wikipedia.org/wiki/Saab_JAS_39_Gripen',
      'http://www.flugzeuginfo.net/acdata_php/acdata_s39_en.php',
    ],
    unlock: { area: 'flygplatsen', missions: 1 },
  },
  {
    id: 'a320',
    name: 'Airbus A320',
    shortName: 'Airbus A320',
    category: 'airliner',
    country: 'Europa (Airbus)',
    swedish: false,
    facts: ['A320 är ett passagerarflygplan.', 'A320 har två motorer under vingarna.', 'A320 flög första gången 1987.'],
    specs: { firstYear: 1987, engines: 2, lengthM: 37.57, wingspanM: 35.8 },
    sources: ['https://sv.wikipedia.org/wiki/Airbus_A320', 'https://en.wikipedia.org/wiki/Airbus_A320_family'],
    unlock: { area: 'flygplatsen', missions: 2 },
  },
  {
    id: 'viggen',
    name: 'Saab 37 Viggen',
    shortName: 'Viggen',
    category: 'fighter',
    country: 'Sverige',
    swedish: true,
    facts: [
      'Viggen är ett svenskt flygplan från Saab.',
      'Viggen har vingar både fram och bak.',
      'Viggen har en motor.',
      'Viggen flög för Sverige från 1972 till 2007.',
    ],
    specs: { firstYear: 1967, engines: 1, lengthM: 16.4, wingspanM: 10.6, topSpeedKmh: 2231 },
    sources: ['https://sv.wikipedia.org/wiki/Saab_37_Viggen', 'https://en.wikipedia.org/wiki/Saab_37_Viggen'],
    unlock: { area: 'flygplatsen', missions: 3 },
  },
  {
    id: 'f16',
    name: 'General Dynamics F-16 Fighting Falcon',
    shortName: 'F-16',
    category: 'fighter',
    country: 'USA',
    swedish: false,
    facts: ['F-16 kommer från USA.', 'F-16 har en motor.', 'F-16 flög första gången 1974.'],
    specs: { firstYear: 1974, engines: 1, lengthM: 15.02, wingspanM: 10 },
    sources: [
      'https://sv.wikipedia.org/wiki/F-16_Fighting_Falcon',
      'https://en.wikipedia.org/wiki/General_Dynamics_F-16_Fighting_Falcon',
    ],
    unlock: { area: 'flygplatsen', missions: 4 },
  },
  {
    id: 'draken',
    name: 'Saab 35 Draken',
    shortName: 'Draken',
    category: 'fighter',
    country: 'Sverige',
    swedish: true,
    facts: [
      'Draken är ett svenskt flygplan från Saab.',
      'Draken har en motor.',
      'Draken kunde flyga dubbelt så fort som ljudet.',
      'Draken flög första gången 1955.',
    ],
    specs: { firstYear: 1955, engines: 1, lengthM: 15.34, wingspanM: 9.42 },
    sources: ['https://sv.wikipedia.org/wiki/Saab_35_Draken', 'https://en.wikipedia.org/wiki/Saab_35_Draken'],
    unlock: { area: 'flygplatsen', missions: 5 },
  },
  {
    id: 'b737',
    name: 'Boeing 737',
    shortName: 'Boeing 737',
    category: 'airliner',
    country: 'USA',
    swedish: false,
    facts: [
      'Boeing 737 är ett passagerarflygplan.',
      'Boeing 737 har två motorer under vingarna.',
      'Det finns fler Boeing 737 än något annat jetflygplan för passagerare.',
    ],
    specs: { firstYear: 1967, engines: 2, lengthM: 39.5, wingspanM: 34.3 },
    sources: ['https://sv.wikipedia.org/wiki/Boeing_737', 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation'],
    unlock: { area: 'flygplatsen', missions: 6 },
  },
  {
    id: 'rafale',
    name: 'Dassault Rafale',
    shortName: 'Rafale',
    category: 'fighter',
    country: 'Frankrike',
    swedish: false,
    facts: ['Rafale kommer från Frankrike.', 'Rafale har två motorer.', 'Rafale har små vingar nära stora vingarna.'],
    specs: { firstYear: 1986, engines: 2, lengthM: 15.27, wingspanM: 10.8, topSpeedKmh: 2205 },
    sources: ['https://sv.wikipedia.org/wiki/Dassault_Rafale'],
    unlock: { area: 'flygplatsen', missions: 7 },
  },
  {
    id: 'saab340',
    name: 'Saab 340',
    shortName: 'Saab 340',
    category: 'airliner',
    country: 'Sverige',
    swedish: true,
    facts: [
      'Saab 340 är ett svenskt passagerarflygplan.',
      'Saab 340 har två propellrar.',
      'Det finns plats för 33 eller 34 passagerare.',
    ],
    specs: { firstYear: 1983, engines: 2, lengthM: 19.73, wingspanM: 21.44, topSpeedKmh: 523 },
    sources: ['https://sv.wikipedia.org/wiki/Saab_340'],
    unlock: { area: 'flygplatsen', missions: 8 },
  },
  {
    id: 'typhoon',
    name: 'Eurofighter Typhoon',
    shortName: 'Typhoon',
    category: 'fighter',
    country: 'Europa (fyra länder)',
    swedish: false,
    facts: [
      'Typhoon byggdes av flera länder i Europa tillsammans.',
      'Typhoon har två motorer.',
      'Typhoon har små vingar längst fram.',
    ],
    specs: { firstYear: 1994, engines: 2, lengthM: 15.96, wingspanM: 10.95, topSpeedKmh: 2495 },
    sources: ['https://sv.wikipedia.org/wiki/Eurofighter_Typhoon'],
    unlock: { area: 'flygplatsen', missions: 9 },
  },
  {
    id: 'fa18',
    name: 'McDonnell Douglas F/A-18 Hornet',
    shortName: 'F/A-18',
    category: 'fighter',
    country: 'USA',
    swedish: false,
    facts: ['F/A-18 kommer från USA.', 'F/A-18 har två motorer.', 'F/A-18 har två stjärtfenor som lutar utåt.'],
    specs: { firstYear: 1978, engines: 2, lengthM: 17.1, wingspanM: 12.3 },
    sources: ['https://sv.wikipedia.org/wiki/F/A-18_Hornet'],
    unlock: { area: 'flygplatsen', missions: 10 },
  },
  {
    id: 'a380',
    name: 'Airbus A380',
    shortName: 'Airbus A380',
    category: 'airliner',
    country: 'Europa (Airbus)',
    swedish: false,
    facts: [
      'A380 har två våningar för passagerare.',
      'A380 har fyra motorer.',
      'A380 är världens största passagerarflygplan.',
    ],
    specs: { firstYear: 2005, engines: 4, lengthM: 72.7, wingspanM: 79.8, topSpeedKmh: 953 },
    sources: ['https://sv.wikipedia.org/wiki/Airbus_A380'],
    unlock: { area: 'flygplatsen', missions: 11 },
  },
  {
    id: 'f15',
    name: 'McDonnell Douglas F-15 Eagle',
    shortName: 'F-15',
    category: 'fighter',
    country: 'USA',
    swedish: false,
    facts: [
      'F-15 kommer från USA.',
      'F-15 har två motorer och två stora stjärtfenor.',
      'F-15 flög första gången 1972.',
    ],
    specs: { firstYear: 1972, engines: 2, lengthM: 19.44, wingspanM: 13 },
    sources: ['https://sv.wikipedia.org/wiki/F-15_Eagle'],
    unlock: { area: 'flygplatsen', missions: 12 },
  },
]
