import type { Vehicle } from '../../core/types'

// Trains (stationen), metro (tunnelbanan) and trams (sparvagnen). Only verified figures are stored;
// anything not confirmed in a source is omitted. Unlock order is ascending per area.
const wiki = (lang: 'sv' | 'en' | 'de', page: string) => `https://${lang}.wikipedia.org/wiki/${page}`

export const RAIL_VEHICLES: Vehicle[] = [
  {
    id: 'x2000',
    name: 'X2000',
    shortName: 'X2000',
    category: 'train',
    country: 'Sverige',
    swedish: true,
    facts: [
      'X2000 är ett svenskt snabbtåg.',
      'Tåget lutar i kurvorna så att det kan köra fort.',
      'Det kör 200 kilometer i timmen.',
    ],
    specs: { firstYear: 1990, topSpeedKmh: 200 },
    sources: [wiki('en', 'X_2000'), wiki('sv', 'X2000')],
    unlock: { area: 'any', missions: 1 },
  },
  {
    id: 'regina',
    name: 'Regina',
    shortName: 'Regina',
    category: 'train',
    country: 'Sverige',
    swedish: true,
    facts: [
      'Regina är ett tåg som bland annat SJ och Mälartåg kör med.',
      'Det har en rund och mjuk nos.',
      'Tåget har flera vagnar som sitter ihop.',
      'Några byggdes i Tyskland.',
    ],
    specs: { firstYear: 2000 },
    sources: [wiki('en', 'Bombardier_Regina'), wiki('sv', 'Regina_(tåg)')],
    unlock: { area: 'stationen', missions: 1 },
  },
  {
    id: 'x60',
    name: 'SL pendeltåg X60',
    shortName: 'Pendeltåget',
    category: 'train',
    country: 'Tyskland',
    swedish: true,
    facts: [
      'Pendeltåget X60 kör i Stockholm.',
      'Det är ett långt tåg med sex vagnar som sitter ihop.',
      'Det började köra år 2005.',
      'Byggd i Tyskland, kör i Stockholm.',
    ],
    specs: { firstYear: 2005, lengthM: 107 },
    sources: [wiki('en', 'SL_X60'), wiki('sv', 'SL_X60')],
    unlock: { area: 'stationen', missions: 2 },
  },
  {
    id: 'x31',
    name: 'Öresundståg X31',
    shortName: 'Öresundståget',
    category: 'train',
    country: 'Sverige',
    swedish: true,
    facts: [
      'Öresundståget kör mellan Sverige och Danmark.',
      'Det åker över Öresundsbron.',
      'Det kan köra 180 kilometer i timmen.',
      'Några byggdes i Tyskland.',
    ],
    specs: { firstYear: 2000, topSpeedKmh: 180, lengthM: 79 },
    sources: [wiki('en', 'Øresundståg'), wiki('sv', 'Öresundståg')],
    unlock: { area: 'stationen', missions: 3 },
  },
  {
    id: 'rc6',
    name: 'Rc6-lok',
    shortName: 'Rc-loket',
    category: 'train',
    country: 'Sverige',
    swedish: true,
    facts: [
      'Rc6 är ett ellok. Det drar tåg med en ström från ledningen ovanför.',
      'Loket har en stång på taket som tar emot strömmen.',
      'Loken började komma år 1985.',
    ],
    specs: { firstYear: 1985, topSpeedKmh: 160, lengthM: 15.4 },
    sources: [wiki('en', 'SJ_Rc')],
    unlock: { area: 'stationen', missions: 4 },
  },
  {
    id: 'iore',
    name: 'Malmlok IORE',
    shortName: 'Malmloket',
    category: 'train',
    country: 'Tyskland',
    swedish: true,
    facts: [
      'Malmloket IORE är extra starkt.',
      'Två lok sitter ihop och drar många tunga vagnar med järnmalm.',
      'De kör i norra Sverige, mellan Kiruna och Narvik.',
      'Byggd i Tyskland, kör i Sverige.',
    ],
    specs: { firstYear: 2001, topSpeedKmh: 80, lengthM: 45.8 },
    sources: [wiki('sv', 'IORE'), wiki('en', 'IORE'), wiki('de', 'IORE')],
    unlock: { area: 'stationen', missions: 5 },
  },
  {
    id: 'c20',
    name: 'Tunnelbanetåg C20',
    shortName: 'C20',
    category: 'metro',
    country: 'Sverige',
    swedish: true,
    facts: [
      'C20 är ett tunnelbanetåg i Stockholm.',
      'Det är silvrigt med blå ränder och har tre vagnar som sitter ihop.',
      'Det började köra år 1998.',
    ],
    specs: { firstYear: 1998, topSpeedKmh: 80, lengthM: 46.5 },
    sources: [wiki('en', 'SL_C20'), wiki('sv', 'SL_C20')],
    unlock: { area: 'tunnelbanan', missions: 1 },
  },
  {
    id: 'c30',
    name: 'Tunnelbanetåg C30',
    shortName: 'C30',
    category: 'metro',
    country: 'Tyskland',
    swedish: true,
    facts: [
      'C30 är ett nyare tunnelbanetåg i Stockholm.',
      'Det började köra år 2020 på röda linjen.',
      'Det kör 80 kilometer i timmen.',
      'Byggd i Tyskland, kör i Stockholm.',
    ],
    specs: { firstYear: 2020, topSpeedKmh: 80 },
    sources: [wiki('en', 'SL_C30'), wiki('sv', 'SL_C30')],
    unlock: { area: 'tunnelbanan', missions: 2 },
  },
  {
    id: 'm32',
    name: 'Spårvagn M32',
    shortName: 'M32',
    category: 'tram',
    country: 'Italien',
    swedish: true,
    facts: [
      'M32 är en spårvagn i Göteborg.',
      'Golvet är lågt, så det är lätt att kliva på.',
      'Spårvagnen tar ström från en ledning ovanför.',
      'Byggd i Italien, kör i Göteborg.',
    ],
    specs: { firstYear: 2006, lengthM: 29.35 },
    sources: [wiki('sv', 'M32_(spårvagn)')],
    unlock: { area: 'sparvagnen', missions: 1 },
  },
  {
    id: 'm33',
    name: 'Spårvagn M33',
    shortName: 'M33',
    category: 'tram',
    country: 'Tyskland och Österrike',
    swedish: true,
    facts: [
      'M33 är en av Göteborgs nyaste spårvagnar.',
      'Den är lång och nästan hela golvet är lågt.',
      'Den började köra år 2020.',
      'Byggd i Tyskland och Österrike, kör i Göteborg.',
    ],
    specs: { firstYear: 2020, topSpeedKmh: 70, lengthM: 33 },
    sources: [wiki('sv', 'M33_(spårvagn)')],
    unlock: { area: 'sparvagnen', missions: 2 },
  },
]
